"""initial schema

Revision ID: 668dc8c860a4
Revises: 
Create Date: 2026-03-09 20:43:38.498998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '668dc8c860a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('spid_session_index', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('sessions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.create_unique_constraint(None, 'sessions', ['spid_session_index'])
    op.drop_column('sessions', 'token')
    op.add_column('users', sa.Column('cf', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['cf'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'cf')
    op.add_column('sessions', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sessions', type_='unique')
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=True)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.drop_column('sessions', 'is_active')
    op.drop_column('sessions', 'created_at')
    op.drop_column('sessions', 'spid_session_index')
    # ### end Alembic commands ###
