"""initial schema

Revision ID: cd624ee6e0ab
Revises: efb87697b02c
Create Date: 2026-03-10 13:41:43.339340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd624ee6e0ab'
down_revision: Union[str, Sequence[str], None] = 'efb87697b02c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saml_requests', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('saml_requests', 'request_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('AuthnRequest', 'LogoutRequest', name='requesttypeenum'),
               nullable=False)
    op.add_column('sessions', sa.Column('session_id', sa.String(), nullable=True))
    op.alter_column('sessions', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.create_unique_constraint(None, 'sessions', ['session_id'])
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'sessions', type_='unique')
    op.alter_column('sessions', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('sessions', 'session_id')
    op.alter_column('saml_requests', 'request_type',
               existing_type=sa.Enum('AuthnRequest', 'LogoutRequest', name='requesttypeenum'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('saml_requests', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
